name: flutter_layout_grid
description: A grid layout system for Flutter, inspired by CSS Grid Layout
version: 0.10.3
homepage: https://github.com/madewithfelt/flutter_layout_grid

environment:
  flutter: '>=1.14.0 <2.0.0'
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  collection: ^1.0.0
  flutter:
    # When the ParentData changes were released
    # https://github.com/flutter/flutter/pull/48541
    sdk: flutter
  meta: ^1.0.0
  quiver: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
