name: flutter_layout_grid
description: A powerful grid layout system for Flutter, optimized for complex user interface design.
version: 0.11.1
homepage: https://github.com/madewithfelt/flutter_layout_grid

environment:
  flutter: '>=1.14.0'
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  collection: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.0.0
  quiver: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
