name: flutter_layout_grid
description: A powerful grid layout system for Flutter, optimized for complex
  user interface design.
version: 2.0.1
homepage: https://github.com/shyndman/flutter_layout_grid

environment:
  flutter: '>=1.25.0'
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  meta: ^1.3.0
  quiver: ^3.0.0

dev_dependencies:
  # Note: 2.0.0 Doesn't work with the current flutter stable 2.10.5/dart 2.16.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
